export let bookTitle: string = "TypeScript Basics";
export const libraryName: string = "My Library";
export let numberOfBooks: number;
export let isLibraryOpen: boolean;
//Libro
export type Book = {
    titulo: string;
    autor: string;
    genero: string;
    idioma: string;
    precio: number;
    formato: string;
    isbn: string;
    descripcion: string;
    estado: string;
    ubicacion: string;
    fecha_publicacion: Date;
    editorial: string;
    paginas: number;
    dimensiones: { ancho: number; profundidad: number; altura: number };
    peso: number;
    disponible: boolean;
};

let titulo: string;
let autor: string;
let genero: string;
let idioma: string;
let precio: number;
let formato: string;
let isbn: string;
let descripcion: string;
let estado: string;
let ubicacion: string;
let fecha_publicacion: Date;
let editorial: string;
let paginas: number;
let dimensiones: [number, number, number]; 
let peso: number;
let disponible: boolean;